### Recuperar todas las personas
GET http://localhost:3001/api/persons

### Mostrar la información del servidor
GET http://localhost:3001/info
### Recuperar una sólo persona
GET http://localhost:3001/api/persons/3
### Recuperar una persona que no existe
GET  http://localhost:3001/api/persons/500000
### Borrar una persona
DELETE http://localhost:3001/api/persons/3
### Añadir una persona
POST https://apiphonebook-ue3u.onrender.com/api/persons
Content-Type: application/json

{
  "name": "John",
  "number": "123456"
}
### Añadir una persona sin nombre
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "123456"
}
### Añadir una persona sin number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "123"
}
### Añadir una persona con nombre repetido
POST https://apiphonebook-ue3u.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "123456"
}