### Recuperar todas las personas
GET http://localhost:3001/api/persons

### Mostrar la información del servidor
GET http://localhost:3001/info
### Recuperar una sólo persona
GET http://localhost:3001/api/persons/3
### Recuperar una persona que no existe
GET  http://localhost:3001/api/persons/500000
### Borrar una persona
DELETE http://localhost:3001/api/persons/3